# Generated by Django 4.2.3 on 2023-08-11 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('extentions', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^([0-9]{1,3}\\.){3}[0-9]{1,3}$'), 'Invalid IP Address')])),
                ('point', models.IntegerField()),
                ('domainIsSpecial', models.BooleanField(default=False)),
                ('domainCountryCode', models.CharField(default='', max_length=30)),
                ('domainAddedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(1, 'Junior'), (2, 'Senior'), (3, 'Expert'), (4, 'Supreme'), (5, 'Defacer'), (6, 'Hacker')])),
                ('color', models.CharField(default='', max_length=50)),
                ('color_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('rank', models.IntegerField(choices=[(1, 'Junior'), (2, 'Senior'), (3, 'Expert'), (4, 'Supreme'), (5, 'Defacer'), (6, 'Hacker')], default=1)),
                ('total_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('content', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
